# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1e4d6b1201f8a233f83318f3c8fcb3cb412c8a201901ecad5bccb660c0841ffa6b63ed01aaededf509dc709b53b5bd9c3ceeb989f8e2f989ef582102233e4c5

test:
  secret_key_base: 897eceebc977bb118c6bd7ffce8967bb5d4e07f2a6062a5c1ad456484c40f8bea64368945fed73a2f50c6f42aa352aa893263ae6333863f13f7c596e86fde86a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
